# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
